url: "https://johanndorn.github.io"
baseurl: '/energieberatung-dorn2.de'

permalink: pretty
title: 'Jekyll Serif'

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/logo.svg"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_services: 6

collections:
  services:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
      type: "services"
    values:
      layout: "service"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md


  colors:
    primary_bg: "#0055A4"
    primary_bg_2: "#DDEEFF"
    primary_text: "#FFFFFF"
    base_bg: "#F5F8FA"
    base_text: "#1A1A1A"
    logo_text: "#0055A4"
    header_text: "#003366"
